[local]
localhost

[mongodb]
mongodb.nagababu.online

[catalogue]
catalogue.nagababu.online

[redis]
redis.nagababu.online

[user]
user.nagababu.online

[cart]
cart.nagababu.online

[mysql]
mysql.nagababu.online

[shipping]
shipping.nagababu.online

[rabbitmq]
rabbitmq.nagababu.online

[frontend]
frontend.nagababu.online

[payment]
payment.nagababu.online


